<?php

/**
 * Implementation of hook_install().
 */
function ca_private_newsletter_install() {
  variable_set('ca_private_newsletter_list_template', 'ca_private_newsletter_list_template_one');
  variable_set('ca_private_newsletter_node_template', 'ca_private_newsletter_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_private_newsletter_uninstall() {
  variable_del('ca_private_newsletter_list_template');
  variable_del('ca_private_newsletter_node_template');
}
