<?php

include_once('ca_private_newsletter.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_private_newsletter_perm() {
  return array('ca_private_newsletter change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_private_newsletter_menu() {
  $items['admin/settings/ca_private_newsletter'] = array(
    'title' => 'CA Private Newsletter: Admin',
    'description' => 'Change the look and feel of the ca_private_newsletter module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_private_newsletter_admin_settings_form'),
    'access arguments' => array('ca_private_newsletter change templates'),
    'file' => 'ca_private_newsletter.admin.inc',
    'file path' => drupal_get_path('module', 'ca_private_newsletter') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_private_newsletter_action_info() {
  return array(
    'ca_private_newsletter_add_private_newsletter_admin_action' => array(
      'type' => 'user',
      'description' => t('Add private newsletter administrator role'),
    ),
    'ca_private_newsletter_remove_private_newsletter_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove private newsletter administrator role'),
    ),
    'ca_private_newsletter_add_private_newsletter_writer_action' => array(
      'type' => 'user',
      'description' => t('Add private newsletter writer role'),
    ),
    'ca_private_newsletter_remove_private_newsletter_writer_action' => array(
      'type' => 'user',
      'description' => t('Remove private newsletter writer role'),
    ),
    'ca_private_newsletter_add_private_newsletter_viewer_action' => array(
      'type' => 'user',
      'description' => t('Add private newsletter viewer role'),
    ),
    'ca_private_newsletter_remove_private_newsletter_viewer_action' => array(
      'type' => 'user',
      'description' => t('Remove private newsletter viewer role'),
    ),
  );
}

function ca_private_newsletter_add_private_newsletter_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_add_private_newsletter_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Private Newsletter Administrator',
  );
  return $form;
}

function ca_private_newsletter_add_private_newsletter_admin_action_submit(&$form, &$form_state) {
  
}

function ca_private_newsletter_remove_private_newsletter_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_remove_private_newsletter_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Private Newsletter Administrator',
  );
  return $form;
}

function ca_private_newsletter_remove_private_newsletter_admin_action_submit(&$form, &$form_state) {
  
}

function ca_private_newsletter_add_private_newsletter_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter writer') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_add_private_newsletter_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Private Newsletter Writer',
  );
  return $form;
}

function ca_private_newsletter_add_private_newsletter_writer_action_submit(&$form, &$form_state) {
  
}

function ca_private_newsletter_remove_private_newsletter_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter writer') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_remove_private_newsletter_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Private Newsletter Writer',
  );
  return $form;
}

function ca_private_newsletter_remove_private_newsletter_writer_action_submit(&$form, &$form_state) {
  
}

function ca_private_newsletter_add_private_newsletter_viewer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter viewer') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_add_private_newsletter_viewer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Private Newsletter Viewer',
  );
  return $form;
}

function ca_private_newsletter_add_private_newsletter_viewer_action_submit(&$form, &$form_state) {
  
}

function ca_private_newsletter_remove_private_newsletter_viewer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'private newsletter viewer') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_private_newsletter_remove_private_newsletter_viewer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Private Newsletter Viewer',
  );
  return $form;
}

function ca_newsletter_remove_private_newsletter_viewer_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_private_newsletter_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_private_newsletter_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_private_newsletter' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_private_newsletter') . "/css/ca_private_newsletter.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_private_newsletter_views_pre_render(&$view) {
  if ($view->name == 'private-newsletter') {
    drupal_add_css(drupal_get_path('module', 'ca_private_newsletter') . "/css/ca_private_newsletter.css", 'module', 'all', FALSE);
  }
}

